#!/bin/bash
#shell script to find sum of n numbers using for loop
echo "Enter Size (n)"
read n
i=1
sum=0
echo "Enter Numbers"
while [$i -le $n]
do
read num    #get number
sum=$((sum+num)) #sum+=num
i=$((i + 1))
i++
done
echo $sum
