#!/usr/bin/env bash
#Write a manage_my_process Bash script that, Indefinitely writes I am alive! to the file /tmp/my_process, In between every I am alive! message, the program should pause for 2 seconds

if [ $1 =='start']
then
    echo "$ >>/var/run/my_process.pid"
    echo "My process started"
elif [ $1 == 'stop']
then 
    echo "$ >>/var/run/my_process.pid"
    echo "My process stopped"
if [$1 == 'restart']
then
    echo "$ >>/var/run/my_process.pid"
    echo "My process restated"
sudo kill 
else 
echo "Usage: manage_my_process {start|stop|restart}"
echo "$$">>|rm -rf manage_my_process_
done
