#!/usr/bin/env bash
#Write Bash (init) script 11-manage_my_process that manages manage_my_process
if [ "$1" == 'start' ]
then
    echo "manage_my_process started"
    echo "$!" > "/var/run/my_process.pid"

elif [ "$1" == 'stop' ]
  then
    echo "manage_my_process stopped"
    pkill -f "./my_process.pid"
    rm "/var/run/my_process.pid"
    
elif [ "$1" == 'restart' ]
then
    echo "manage_my_process restarted"
    pkill -f "./my_process.pid"
    rm "/var/run/my_process.pid"
    ./manage_my_process &
    echo "$!" > "/var/run/my_process.pid"

else
    echo "Usage: manage_my_process {start|stop|restart}"
fi

