#!/usr/bin/env bash
# Script that display To infinity and beyond indefinitely, With a sleep 2 in between each iteration, I am invincible!!!
trap 
while true; do
    'echo "I am invincible!!!"'SIGTERM
    sleep 2
done
do
    echo "To infinity and beyond"
sleep 2    
done
