#!/usr/bin/env bash
#Write a manage_my_process Bash script that: Indefinitely writes I am alive! to the file /tmp/my_process, In between every I am alive! message, the program should pause for 2 seconds, Write Bash (init) script 11-manage_my_process that manages manage_my_process.

manage_my_process
while  true :
do
echo "I am alive!
>>/tmp/my_process
sleep 2
done
 

if [$1== 'start']
then 
     echo "$" >/var/run/my_process.pid
     echo "manage_my_process started"
elif [$1=='start']
else 
echo "usage :manage_my_process ((start/stop/restart))
echo "$$" > |rm -rf |my_process_started

